# https://taskfile.dev

version: '3'

vars:
  NOW:
    sh: date '+%d-%b-%H%M%S'

tasks:

  init:
    desc: init python environment
    cmds:
      - rm -rf .venv
      - python3 -m venv .venv
      - .venv/bin/python3 -m pip install -r requirements.txt
      - source .venv/bin/activate
  
  start:
    desc: start local dev
    cmds:
      - .venv/bin/python3 -m gunicorn wsgi:application
  
  save:
    desc: save on github
    cmds:
      - git pull
      - git add .
      - git commit -m '{{.NOW}}'
      - git push
